### ISSUE TITLE
Breaking change in ostruct 0.3.0

### ISSUE THREAD

**Issue by tagliala** [ruby/ostruct#32]
Hi,

just want to report that commit 9cd88953f93ae60d59a5870ee8d9f3de21e8b692 introduced a breaking change with the following use case:

```rb
class MyClass < OpenStruct
  def initialize(hash)
    super({})

    hash.each do |key, value|
      new_ostruct_member!(key)
      self[key] = value
    end
  end
end

puts MyClass.new('id' => 10).id
```

Ruby 2.7.4 output: `10`
Ruby 3.0.2 output: ` `

**Comment by marcandre** [comment]
Thanks for writing, and sorry if this is an inconvenience.

This is due to `new_ostruct_member!` that assumes its argument is a symbol.

Solutions:
1) Remove your `initialize` method altogether, as it serves no purpose I can see
2) Or simplify it with `super(hash)`
3) Or remove the call to `new_ostruct_member!` altogether
4) Or convert your `key` with `to_sym`
5) Or pass only symbol keys

Comments:
* Calling private methods of classes you don't own is a bad idea
* `ostruct` in general is not such a great idea (see caveats section)
