### ISSUE TITLE
OpenStruct should not alias :method or :public_send on JRuby

### ISSUE THREAD

**Issue by ikaronen-relex** [ruby/ostruct#61]
On JRuby 9.4, running `require 'ostruct'` in verbose mode generates warnings saying that OpenStruct#public_send and OpenStruct#method "accesses caller method's state and should not be aliased":

```ruby
irb(main):001> $VERBOSE = true
=> true
irb(main):002> require 'ostruct'
.../9.4.6.0/gems/ostruct-0.6.0/lib/ostruct.rb:478: warning: OpenStruct#public_send accesses caller method's state and should not be aliased
.../9.4.6.0/gems/ostruct-0.6.0/lib/ostruct.rb:478: warning: OpenStruct#method accesses caller method's state and should not be aliased
=> true
```

This seems to be essentially the same issue as https://github.com/ruby/ostruct/issues/30 (and related to https://github.com/ruby/ostruct/issues/40), just with more methods now generating these warnings.

 (Apparently this warning started to be emitted for `method` and `public_send` as a side effect of the implementation of refinements in JRuby 9.4.0.0 in https://github.com/jruby/jruby/commit/dbf10a1cdcf208f4fc20bed446d334b0f4cda971 and https://github.com/jruby/jruby/commit/3a76d29c4f7c1437479bb364a5fd33898faf1805.)

Neither `public_send!` nor `method!` seem to be used anywhere in the actual OpenStruct code, so simply adding them to the JRuby exclusion list at https://github.com/ruby/ostruct/blob/v0.6.0/lib/ostruct.rb#L473 should be OK.

However, `method!` _is_ use in one test at https://github.com/ruby/ostruct/blob/v0.6.0/test/ostruct/test_ostruct.rb#L281. That test might need to be skipped on JRuby, unless it can be rewritten not to call `method!`.

**Comment by headius** [comment]
I actually committed a fix for 9.4.7.0 that works around this aliasing in a slightly hacky way: https://github.com/jruby/jruby/pull/8206

The idea here is that since ostruct really wants to alias a whole bunch of frame-aware methods, I just go ahead and add the bang versions of those methods at boot time. This prevents the aliases from causing trouble because those methods aren't already marked as needing frame access. 

I believe that with 9.4.7.0 you do not see these warnings for any methods anymore, and the exclusions in ostruct could be removed.
